<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Планирани съобщения';
$labels['queue_cancel_ok'] = 'Отменен';
$labels['queue_resched_ok'] = 'Пренасрочен';
$labels['scheduled'] = 'Планирано';
$labels['schedulefail'] = 'Невъзможност за планиране';
$labels['invaliddatetime'] = 'Невалидна дата/час';
$labels['scheduledmessages'] = 'Планирани съобщения';
$labels['scheduledsending'] = 'Планирано изпращане';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Планирано в';
$labels['subject'] = 'Тема';
$labels['to'] = 'За';
$labels['status'] = 'Статус';
$labels['created_at'] = 'Създаден в';
$labels['delete'] = 'Изтриване';
?>
