<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Naplánované zprávy';
$labels['queue_cancel_ok'] = 'Zrušeno';
$labels['queue_resched_ok'] = 'Přeloženo na';
$labels['scheduled'] = 'Plánované';
$labels['schedulefail'] = 'Nelze naplánovat';
$labels['invaliddatetime'] = 'Neplatné datum/čas';
$labels['scheduledmessages'] = 'Naplánované zprávy';
$labels['scheduledsending'] = 'Plánované odesílání';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Naplánováno na';
$labels['subject'] = 'Předmět';
$labels['to'] = 'Na';
$labels['status'] = 'Stav';
$labels['created_at'] = 'Vytvořeno v';
?>
