<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Planlagte beskeder';
$labels['queue_cancel_ok'] = 'Annulleret';
$labels['queue_resched_ok'] = 'Udsat';
$labels['scheduled'] = 'Planlagt';
$labels['schedulefail'] = 'Kan ikke planlægge';
$labels['invaliddatetime'] = 'Ugyldig dato/tid';
$labels['scheduledmessages'] = 'Planlagte beskeder';
$labels['scheduledsending'] = 'Planlagt afsendelse';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Planlagt til';
$labels['subject'] = 'Emne';
$labels['to'] = 'Til';
$labels['status'] = 'Status';
$labels['created_at'] = 'Oprettet på';
$labels['delete'] = 'Slet';
?>
