<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Geplante Nachrichten';
$labels['queue_cancel_ok'] = 'Abgesagt';
$labels['queue_resched_ok'] = 'Umgeplant';
$labels['scheduled'] = 'Geplant';
$labels['schedulefail'] = 'Keine Zeitplanung möglich';
$labels['invaliddatetime'] = 'Ungültiges Datum/Uhrzeit';
$labels['scheduledmessages'] = 'Geplante Nachrichten';
$labels['scheduledsending'] = 'Geplantes Versenden';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Geplant am';
$labels['subject'] = 'Thema';
$labels['to'] = 'An';
$labels['status'] = 'Status';
$labels['created_at'] = 'Erstellt am';
$labels['delete'] = 'Löschen';
?>
