<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Προγραμματισμένα μηνύματα';
$labels['queue_cancel_ok'] = 'Ακυρώθηκε';
$labels['queue_resched_ok'] = 'Επαναπρογραμματισμένο';
$labels['scheduled'] = 'Προγραμματισμένο';
$labels['schedulefail'] = 'Αδυναμία προγραμματισμού';
$labels['invaliddatetime'] = 'Μη έγκυρη ημερομηνία/ώρα';
$labels['scheduledmessages'] = 'Προγραμματισμένα μηνύματα';
$labels['scheduledsending'] = 'Προγραμματισμένη αποστολή';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Προγραμματισμένο σε';
$labels['subject'] = 'Θέμα';
$labels['to'] = 'Προς';
$labels['status'] = 'Κατάσταση';
$labels['created_at'] = 'Δημιουργήθηκε στο';
?>
