<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Scheduled messages';
$labels['queue_cancel_ok'] = 'Canceled';
$labels['queue_resched_ok'] = 'Rescheduled';
$labels['scheduled'] = 'Scheduled';
$labels['schedulefail'] = 'Unable to schedule';
$labels['invaliddatetime'] = 'Invalid date/time';
$labels['scheduledmessages'] = 'Scheduled Messages';
$labels['scheduledsending'] = 'Scheduled Sending';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Scheduled At';
$labels['subject'] = 'Subject';
$labels['to'] = 'To';
$labels['status'] = 'Status';
$labels['created_at'] = 'Created At';
?>
