<?php
$labels = array(
  'scheduled_queue_title' => 'Scheduled messages',
  'queue_cancel_ok' => 'Canceled',
  'queue_resched_ok' => 'Rescheduled',
  'scheduled' => 'Scheduled',
  'schedulefail' => 'Unable to schedule',
  'invaliddatetime' => 'Invalid date/time',
  'scheduledmessages' => 'Scheduled Messages',
  'scheduledsending' => 'Scheduled Sending',
  'id' => 'ID',
  'scheduled_at' => 'Scheduled At',
  'subject' => 'Subject',
  'to' => 'To',
  'status' => 'Status',
  'created_at' => 'Created At',
  'delete' => 'Delete',
);
