<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Mensajes programados';
$labels['queue_cancel_ok'] = 'Cancelado';
$labels['queue_resched_ok'] = 'Reprogramado';
$labels['scheduled'] = 'Programado';
$labels['schedulefail'] = 'No se puede programar';
$labels['invaliddatetime'] = 'Fecha/hora no válida';
$labels['scheduledmessages'] = 'Mensajes programados';
$labels['scheduledsending'] = 'Envío programado';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Programado en';
$labels['subject'] = 'Asunto';
$labels['to'] = 'A';
$labels['status'] = 'Estado';
$labels['created_at'] = 'Creado en';
?>
