<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Ajastatud sõnumid';
$labels['queue_cancel_ok'] = 'Tühistatud';
$labels['queue_resched_ok'] = 'Ümberplaneeritud';
$labels['scheduled'] = 'Planeeritud';
$labels['schedulefail'] = 'Ei ole võimalik ajakava koostada';
$labels['invaliddatetime'] = 'Vale kuupäev/kellaaeg';
$labels['scheduledmessages'] = 'Plaanilised sõnumid';
$labels['scheduledsending'] = 'Planeeritud saatmine';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Planeeritud aadressil';
$labels['subject'] = 'Teema';
$labels['to'] = 'Aadressile';
$labels['status'] = 'Staatus';
$labels['created_at'] = 'Loodud aadressil';
$labels['delete'] = 'Kustuta';
?>
