<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Ajastetut viestit';
$labels['queue_cancel_ok'] = 'Peruutettu';
$labels['queue_resched_ok'] = 'Uudelleen suunniteltu';
$labels['scheduled'] = 'Aikataulutettu';
$labels['schedulefail'] = 'Aikatauluttaminen ei onnistu';
$labels['invaliddatetime'] = 'Virheellinen päivämäärä/aika';
$labels['scheduledmessages'] = 'Ajastetut viestit';
$labels['scheduledsending'] = 'Ajastettu lähettäminen';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Aikataulutettu klo';
$labels['subject'] = 'Aihe';
$labels['to'] = 'Osoitteeseen';
$labels['status'] = 'Tila';
$labels['created_at'] = 'Created at';
?>
