<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Messages programmés';
$labels['queue_cancel_ok'] = 'Annulé';
$labels['queue_resched_ok'] = 'Reporté';
$labels['scheduled'] = 'Prévu';
$labels['schedulefail'] = 'Impossible de programmer';
$labels['invaliddatetime'] = 'Date/heure invalide';
$labels['scheduledmessages'] = 'Messages programmés';
$labels['scheduledsending'] = 'Envoi programmé';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Prévu à';
$labels['subject'] = 'Sujet';
$labels['to'] = 'Pour';
$labels['status'] = 'Statut';
$labels['created_at'] = 'Créé à';
$labels['delete'] = 'Supprimer';
?>
