<?php
$labels = array();
$labels['scheduled_queue_title'] = 'הודעות מתוזמנות';
$labels['queue_cancel_ok'] = 'בוטל';
$labels['queue_resched_ok'] = 'תאריך חדש';
$labels['scheduled'] = 'מתוכנן';
$labels['schedulefail'] = 'לא ניתן לתזמן';
$labels['invaliddatetime'] = 'תאריך/שעה לא חוקיים';
$labels['scheduledmessages'] = 'הודעות מתוזמנות';
$labels['scheduledsending'] = 'שליחה מתוזמנת';
$labels['id'] = 'תעודת זהות';
$labels['scheduled_at'] = 'מתוכנן ב';
$labels['subject'] = 'נושא';
$labels['to'] = 'ל';
$labels['status'] = 'סטטוס';
$labels['created_at'] = 'נוצר ב';
?>
