<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Ütemezett üzenetek';
$labels['queue_cancel_ok'] = 'Törölt';
$labels['queue_resched_ok'] = 'Átütemezett';
$labels['scheduled'] = 'Tervezett';
$labels['schedulefail'] = 'Nem lehet ütemezni';
$labels['invaliddatetime'] = 'Érvénytelen dátum/idő';
$labels['scheduledmessages'] = 'Ütemezett üzenetek';
$labels['scheduledsending'] = 'Ütemezett küldés';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Beosztva';
$labels['subject'] = 'Tárgy';
$labels['to'] = 'A  címre';
$labels['status'] = 'Állapot';
$labels['created_at'] = 'Létrehozva';
$labels['delete'] = 'Töröl';
?>
