<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Messaggi programmati';
$labels['queue_cancel_ok'] = 'Annullato';
$labels['queue_resched_ok'] = 'Riprogrammato';
$labels['scheduled'] = 'In programma';
$labels['schedulefail'] = 'Impossibile programmare';
$labels['invaliddatetime'] = 'Data/ora non valida';
$labels['scheduledmessages'] = 'Messaggi programmati';
$labels['scheduledsending'] = 'Invio programmato';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'In programma a';
$labels['subject'] = 'Oggetto';
$labels['to'] = 'A';
$labels['status'] = 'Stato';
$labels['created_at'] = 'Creato a';
$labels['delete'] = 'Eliminare';
?>
