<?php
$labels = array();
$labels['scheduled_queue_title'] = 'スケジュールされたメッセージ';
$labels['queue_cancel_ok'] = 'キャンセル';
$labels['queue_resched_ok'] = '予定変更';
$labels['scheduled'] = '予定';
$labels['schedulefail'] = 'スケジュールが組めない';
$labels['invaliddatetime'] = '無効な日時';
$labels['scheduledmessages'] = 'スケジュールされたメッセージ';
$labels['scheduledsending'] = '予約送信';
$labels['id'] = '身分証明書';
$labels['scheduled_at'] = '予定';
$labels['subject'] = 'テーマ';
$labels['to'] = 'へ';
$labels['status'] = 'ステータス';
$labels['created_at'] = '作成日時';
$labels['delete'] = '消去';
?>
