<?php
$labels = array();
$labels['scheduled_queue_title'] = '예약된 메시지';
$labels['queue_cancel_ok'] = '취소됨';
$labels['queue_resched_ok'] = '일정 변경';
$labels['scheduled'] = '예약됨';
$labels['schedulefail'] = '예약할 수 없습니다';
$labels['invaliddatetime'] = '잘못된 날짜/시간';
$labels['scheduledmessages'] = '예약된 메시지';
$labels['scheduledsending'] = '예약 전송';
$labels['id'] = 'ID';
$labels['scheduled_at'] = '예약된 날짜';
$labels['subject'] = '제목';
$labels['to'] = 'To';
$labels['status'] = '상태';
$labels['created_at'] = '만든 곳';
$labels['delete'] = '삭제';
?>
