<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Suplanuoti pranešimai';
$labels['queue_cancel_ok'] = 'Atšauktas';
$labels['queue_resched_ok'] = 'Perplanuota';
$labels['scheduled'] = 'Suplanuota';
$labels['schedulefail'] = 'Nepavyksta suplanuoti';
$labels['invaliddatetime'] = 'Netinkama data ir laikas';
$labels['scheduledmessages'] = 'Suplanuoti pranešimai';
$labels['scheduledsending'] = 'Suplanuotas siuntimas';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Suplanuota ne';
$labels['subject'] = 'Tema';
$labels['to'] = 'Į';
$labels['status'] = 'Statusas';
$labels['created_at'] = 'Sukurta ne';
?>
