<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Plānotie ziņojumi';
$labels['queue_cancel_ok'] = 'Atcelts';
$labels['queue_resched_ok'] = 'Pārplānots';
$labels['scheduled'] = 'Plānotais';
$labels['schedulefail'] = 'Nevar ieplānot';
$labels['invaliddatetime'] = 'Nederīgs datums/laiks';
$labels['scheduledmessages'] = 'Plānotie ziņojumi';
$labels['scheduledsending'] = 'Plānotā sūtīšana';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Plānots plkst';
$labels['subject'] = 'Temats';
$labels['to'] = 'Uz';
$labels['status'] = 'Statuss';
$labels['created_at'] = 'Izveidots pie';
$labels['delete'] = 'Dzēst';
?>
