<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Geplande berichten';
$labels['queue_cancel_ok'] = 'Geannuleerd';
$labels['queue_resched_ok'] = 'Verpland';
$labels['scheduled'] = 'Gepland';
$labels['schedulefail'] = 'Kan niet plannen';
$labels['invaliddatetime'] = 'Ongeldige datum/tijd';
$labels['scheduledmessages'] = 'Geplande berichten';
$labels['scheduledsending'] = 'Geplande verzending';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Gepland op';
$labels['subject'] = 'Onderwerp';
$labels['to'] = 'Naar';
$labels['status'] = 'Status';
$labels['created_at'] = 'Gemaakt op';
$labels['delete'] = 'Dzēst';
?>
