<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Planlagte meldinger';
$labels['queue_cancel_ok'] = 'Avlyst';
$labels['queue_resched_ok'] = 'Utsatt';
$labels['scheduled'] = 'Planlagt';
$labels['schedulefail'] = 'Kan ikke planlegge';
$labels['invaliddatetime'] = 'Ugyldig dato/tid';
$labels['scheduledmessages'] = 'Planlagte meldinger';
$labels['scheduledsending'] = 'Planlagt sending';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Planlagt til';
$labels['subject'] = 'Emne';
$labels['to'] = 'Til';
$labels['status'] = 'Status';
$labels['created_at'] = 'Opprettet på';
$labels['delete'] = 'Slett';
?>
