<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Zaplanowane wiadomości';
$labels['queue_cancel_ok'] = 'Anulowane';
$labels['queue_resched_ok'] = 'Przełożone';
$labels['scheduled'] = 'Zaplanowane';
$labels['schedulefail'] = 'Nie można zaplanować';
$labels['invaliddatetime'] = 'Nieprawidłowa data/godzina';
$labels['scheduledmessages'] = 'Zaplanowane wiadomości';
$labels['scheduledsending'] = 'Wysyłanie zaplanowane';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Zaplanowane na';
$labels['subject'] = 'Przedmiot';
$labels['to'] = 'Do';
$labels['status'] = 'Status';
$labels['created_at'] = 'Utworzono w';
?>
