<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Mensagens programadas';
$labels['queue_cancel_ok'] = 'Cancelado';
$labels['queue_resched_ok'] = 'Reagendado';
$labels['scheduled'] = 'Programado';
$labels['schedulefail'] = 'Não é possível agendar';
$labels['invaliddatetime'] = 'Data/hora inválida';
$labels['scheduledmessages'] = 'Mensagens programadas';
$labels['scheduledsending'] = 'Envio programado';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Programado em';
$labels['subject'] = 'Assunto';
$labels['to'] = 'Para';
$labels['status'] = 'Status';
$labels['created_at'] = 'Criado em';
$labels['delete'] = 'Excluir';
?>
