<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Mesaje programate';
$labels['queue_cancel_ok'] = 'Anulat';
$labels['queue_resched_ok'] = 'Reprogramat';
$labels['scheduled'] = 'Programat';
$labels['schedulefail'] = 'Imposibilitatea de a programa';
$labels['invaliddatetime'] = 'Data/ora invalidă';
$labels['scheduledmessages'] = 'Mesaje programate';
$labels['scheduledsending'] = 'Trimitere programată';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Programat la';
$labels['subject'] = 'Subiect';
$labels['to'] = 'La';
$labels['status'] = 'Statut';
$labels['created_at'] = 'Creat la';
?>
