<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Запланированные сообщения';
$labels['queue_cancel_ok'] = 'Отменено';
$labels['queue_resched_ok'] = 'Перенесено';
$labels['scheduled'] = 'Запланировано';
$labels['schedulefail'] = 'Невозможно составить расписание';
$labels['invaliddatetime'] = 'Неверная дата/время';
$labels['scheduledmessages'] = 'Запланированные сообщения';
$labels['scheduledsending'] = 'Отправка по расписанию';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Запланировано на';
$labels['subject'] = 'Тема';
$labels['to'] = 'На';
$labels['status'] = 'Статус';
$labels['created_at'] = 'Создано в';
?>
