<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Naplánované správy';
$labels['queue_cancel_ok'] = 'Zrušené';
$labels['queue_resched_ok'] = 'Zmena termínu';
$labels['scheduled'] = 'Plánované';
$labels['schedulefail'] = 'Nemožnosť naplánovať';
$labels['invaliddatetime'] = 'Neplatný dátum/čas';
$labels['scheduledmessages'] = 'Naplánované správy';
$labels['scheduledsending'] = 'Plánované odosielanie';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Naplánované na';
$labels['subject'] = 'Predmet';
$labels['to'] = 'Na';
$labels['status'] = 'Stav';
$labels['created_at'] = 'Vytvorené v';
?>
