<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Načrtovana sporočila';
$labels['queue_cancel_ok'] = 'Odpovedano';
$labels['queue_resched_ok'] = 'Prestavljen termin';
$labels['scheduled'] = 'Načrtovani';
$labels['schedulefail'] = 'Ni mogoče načrtovati';
$labels['invaliddatetime'] = 'Nepravilen datum/čas';
$labels['scheduledmessages'] = 'Načrtovana sporočila';
$labels['scheduledsending'] = 'Načrtovano pošiljanje';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Načrtovano na';
$labels['subject'] = 'Zadeva';
$labels['to'] = 'Na naslov';
$labels['status'] = 'Status';
$labels['created_at'] = 'Ustvarjeno na';
$labels['delete'] = 'Izbriši';
?>
