<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Schemalagda meddelanden';
$labels['queue_cancel_ok'] = 'Annullerad';
$labels['queue_resched_ok'] = 'Omplanerad';
$labels['scheduled'] = 'Planerad';
$labels['schedulefail'] = 'Kan inte schemaläggas';
$labels['invaliddatetime'] = 'Ogiltigt datum/tid';
$labels['scheduledmessages'] = 'Schemalagda meddelanden';
$labels['scheduledsending'] = 'Schemalagd sändning';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Planerad till';
$labels['subject'] = 'Ämne';
$labels['to'] = 'Till';
$labels['status'] = 'Status';
$labels['created_at'] = 'Skapad vid';
$labels['delete'] = 'Radera';
?>
