<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Zamanlanmış mesajlar';
$labels['queue_cancel_ok'] = 'İptal edildi';
$labels['queue_resched_ok'] = 'Yeniden planlandı';
$labels['scheduled'] = 'Planlanmış';
$labels['schedulefail'] = 'Programlanamıyor';
$labels['invaliddatetime'] = 'Geçersiz tarih/saat';
$labels['scheduledmessages'] = 'Zamanlanmış Mesajlar';
$labels['scheduledsending'] = 'Planlanmış Gönderme';
$labels['id'] = 'KIMLIK';
$labels['scheduled_at'] = 'Planlanan';
$labels['subject'] = 'Konu';
$labels['to'] = 'Için';
$labels['status'] = 'Durum';
$labels['created_at'] = 'Şu Adreste Oluşturuldu';
$labels['delete'] = 'Silmek';
?>
