<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Повідомлення за розкладом';
$labels['queue_cancel_ok'] = 'Скасовано';
$labels['queue_resched_ok'] = 'Перенесено';
$labels['scheduled'] = 'Заплановано';
$labels['schedulefail'] = 'Неможливо запланувати';
$labels['invaliddatetime'] = 'Невірна дата/час';
$labels['scheduledmessages'] = 'Заплановані повідомлення';
$labels['scheduledsending'] = 'Запланована відправка';
$labels['id'] = 'ІДЕНТИФІКАТОР';
$labels['scheduled_at'] = 'Заплановано на';
$labels['subject'] = 'Тема';
$labels['to'] = 'До';
$labels['status'] = 'Статус';
$labels['created_at'] = 'Створено в';
?>
