<?php
$labels = array();
$labels['scheduled_queue_title'] = 'Thông báo được lên lịch';
$labels['queue_cancel_ok'] = 'Đã hủy';
$labels['queue_resched_ok'] = 'Được dời lại';
$labels['scheduled'] = 'Được lên lịch';
$labels['schedulefail'] = 'Không thể lên lịch';
$labels['invaliddatetime'] = 'Ngày/giờ không hợp lệ';
$labels['scheduledmessages'] = 'Thông báo đã lên lịch';
$labels['scheduledsending'] = 'Gửi theo lịch trình';
$labels['id'] = 'ID';
$labels['scheduled_at'] = 'Được lên lịch vào';
$labels['subject'] = 'Chủ đề';
$labels['to'] = 'Để';
$labels['status'] = 'Trạng thái';
$labels['created_at'] = 'Được tạo vào';
$labels['delete'] = 'Xóa bỏ';
?>
