<?php
$labels = array();
$labels['scheduled_queue_title'] = '预定信息';
$labels['queue_cancel_ok'] = '已取消';
$labels['queue_resched_ok'] = '改期';
$labels['scheduled'] = '计划';
$labels['schedulefail'] = '无法安排';
$labels['invaliddatetime'] = '无效日期/时间';
$labels['scheduledmessages'] = '预定信息';
$labels['scheduledsending'] = '计划发送';
$labels['id'] = '身份证';
$labels['scheduled_at'] = '计划于';
$labels['subject'] = '主题';
$labels['to'] = '至';
$labels['status'] = '现状';
$labels['created_at'] = '创建于';
?>
